"""
UAV Network Components
Implements UAV entities, GBS nodes, and network infrastructure
"""

import numpy as np
from config import Config


class UAV:
    """
    Represents a single UAV in the network

    Attributes:
        uav_id: Unique identifier for the UAV
        location: (x, y, z) coordinates
        battery_level: Current battery percentage (0-100)
        assigned_gbs: ID of associated Ground Base Station
        onboard_cache: Dictionary storing cached data
        computing_capacity: Available CPU cycles
        tasks: List of task IDs generated by this UAV
    """

    def __init__(self, uav_id, location=None, assigned_gbs=0):
        self.uav_id = uav_id
        self.location = location if location is not None else self._random_location()
        self.battery_level = np.random.uniform(70, 100)  # Start with 70-100% battery
        self.assigned_gbs = assigned_gbs
        self.onboard_cache = {}  # Static data like maps
        self.computing_capacity = Config.F_UAV
        self.tasks = []

    def _random_location(self):
        """Generate random 3D location for UAV"""
        x = np.random.uniform(0, 1000)  # meters
        y = np.random.uniform(0, 1000)  # meters
        z = Config.UAV_HEIGHT  # Fixed altitude
        return (x, y, z)

    def update_battery(self, energy_consumed):
        """
        Update battery level based on energy consumption

        Args:
            energy_consumed: Energy in Joules
        """
        # Simple battery model: 1000J = 1% battery
        battery_decrease = energy_consumed / 1000.0
        self.battery_level = max(0, self.battery_level - battery_decrease)

    def add_to_cache(self, key, value):
        """Add static data to UAV cache"""
        self.onboard_cache[key] = value

    def check_cache(self, key):
        """Check if data exists in cache"""
        return key in self.onboard_cache

    def get_state(self):
        """Get current UAV state for Digital Twin"""
        return {
            'uav_id': self.uav_id,
            'location': self.location,
            'battery_level': self.battery_level,
            'assigned_gbs': self.assigned_gbs,
            'cache_size': len(self.onboard_cache),
            'computing_capacity': self.computing_capacity,
            'num_tasks': len(self.tasks)
        }


class GBS:
    """
    Ground Base Station

    Attributes:
        gbs_id: Unique identifier
        location: (x, y) coordinates
        coverage_radius: Coverage area radius in meters
        computing_capacity: CPU frequency
        cache: Dictionary for local environmental data
        connected_uavs: List of UAV IDs within coverage
        task_load: Current number of tasks being processed
    """

    def __init__(self, gbs_id, location=None):
        self.gbs_id = gbs_id
        self.location = location if location is not None else self._random_location()
        self.coverage_radius = 500  # 500 meters coverage
        self.computing_capacity = Config.F_GBS
        self.cache = {}  # Local environmental data
        self.connected_uavs = []
        self.task_load = 0

    def _random_location(self):
        """Generate random 2D location for GBS"""
        x = np.random.uniform(0, 1000)
        y = np.random.uniform(0, 1000)
        return (x, y)

    def is_in_coverage(self, uav_location):
        """Check if UAV is within coverage area"""
        dx = uav_location[0] - self.location[0]
        dy = uav_location[1] - self.location[1]
        distance = np.sqrt(dx**2 + dy**2)
        return distance <= self.coverage_radius

    def add_to_cache(self, key, value):
        """Add data to GBS cache"""
        self.cache[key] = value

    def check_cache(self, key):
        """Check if data exists in cache"""
        return key in self.cache

    def update_task_load(self, task_count):
        """Update the number of tasks assigned to this GBS"""
        self.task_load = task_count

    def get_state(self):
        """Get current GBS state for Digital Twin"""
        return {
            'gbs_id': self.gbs_id,
            'location': self.location,
            'computing_capacity': self.computing_capacity,
            'cache_size': len(self.cache),
            'connected_uavs': len(self.connected_uavs),
            'task_load': self.task_load
        }


class MECServer:
    """
    Mobile Edge Computing Server

    Aggregates multiple GBS nodes and provides higher computing capacity
    """

    def __init__(self, mec_id, associated_gbs_ids):
        self.mec_id = mec_id
        self.associated_gbs_ids = associated_gbs_ids  # List of GBS IDs
        self.computing_capacity = Config.F_MEC
        self.cache = {}  # Aggregated cache from all GBS
        self.task_load = 0

    def add_to_cache(self, key, value):
        """Add data to MEC cache"""
        self.cache[key] = value

    def check_cache(self, key):
        """Check if data exists in cache"""
        return key in self.cache

    def aggregate_gbs_cache(self, gbs_nodes):
        """Aggregate cache data from all associated GBS"""
        for gbs in gbs_nodes:
            if gbs.gbs_id in self.associated_gbs_ids:
                self.cache.update(gbs.cache)

    def get_state(self):
        """Get current MEC state for Digital Twin"""
        return {
            'mec_id': self.mec_id,
            'associated_gbs': self.associated_gbs_ids,
            'computing_capacity': self.computing_capacity,
            'cache_size': len(self.cache),
            'task_load': self.task_load
        }


class CloudServer:
    """
    Cloud Server with virtually unlimited resources
    """

    def __init__(self):
        self.computing_capacity = Config.F_CLOUD
        self.cache = {}  # Complete data repository
        self.task_load = 0

    def add_to_cache(self, key, value):
        """Add data to cloud cache (always available)"""
        self.cache[key] = value

    def check_cache(self, key):
        """Cloud has all data"""
        return True  # Cloud always has the data

    def get_state(self):
        """Get current cloud state for Digital Twin"""
        return {
            'computing_capacity': self.computing_capacity,
            'cache_size': len(self.cache),
            'task_load': self.task_load
        }


class CacheSystem:
    """
    Multi-level caching system for the UAV network

    Implements hierarchical cache lookup:
    UAV cache -> GBS cache -> MEC cache -> Cloud
    """

    def __init__(self, uavs, gbs_nodes, mec_servers, cloud):
        self.uavs = uavs
        self.gbs_nodes = gbs_nodes
        self.mec_servers = mec_servers
        self.cloud = cloud

    def lookup(self, task_id, uav_id):
        """
        Perform hierarchical cache lookup

        Args:
            task_id: ID of the task/data being requested
            uav_id: ID of the requesting UAV

        Returns:
            Tuple (location, hit) where location is where data was found
            and hit is boolean indicating cache hit
        """
        uav = self.uavs[uav_id]

        # Level 1: Check UAV cache
        if uav.check_cache(task_id):
            return (Config.LOC_LOCAL, True)

        # Level 2: Check assigned GBS cache
        gbs = self.gbs_nodes[uav.assigned_gbs]
        if gbs.check_cache(task_id):
            return (Config.LOC_GBS, True)

        # Level 3: Check MEC cache
        for mec in self.mec_servers:
            if uav.assigned_gbs in mec.associated_gbs_ids:
                if mec.check_cache(task_id):
                    return (Config.LOC_MEC, True)
                break

        # Level 4: Cloud always has the data
        return (Config.LOC_CLOUD, True)

    def populate_static_caches(self):
        """
        Populate caches with static data
        UAVs get map data, GBS get local environmental data
        """
        # Populate UAV caches with static map data
        for uav in self.uavs:
            for i in range(5):  # Add 5 static map entries
                uav.add_to_cache(f'map_{i}', f'map_data_{i}')

        # Populate GBS caches with local environmental data
        for gbs in self.gbs_nodes:
            for i in range(10):  # Add 10 local data entries
                gbs.add_to_cache(f'env_{gbs.gbs_id}_{i}', f'env_data_{i}')

        # MEC aggregates from GBS
        for mec in self.mec_servers:
            mec.aggregate_gbs_cache(self.gbs_nodes)

        # Cloud gets everything
        for uav in self.uavs:
            self.cloud.cache.update(uav.onboard_cache)
        for gbs in self.gbs_nodes:
            self.cloud.cache.update(gbs.cache)


if __name__ == "__main__":
    # Test UAV network components
    print("Testing UAV Network Components")
    print("=" * 60)

    # Create UAVs
    print("\n1. Creating UAVs...")
    uavs = [UAV(i, assigned_gbs=i % 3) for i in range(10)]
    print(f"Created {len(uavs)} UAVs")

    # Create GBS
    print("\n2. Creating GBS...")
    gbs_nodes = [GBS(i) for i in range(3)]
    print(f"Created {len(gbs_nodes)} GBS nodes")

    # Create MEC
    print("\n3. Creating MEC...")
    mec = MECServer(0, [0, 1, 2])
    print(f"Created MEC server")

    # Create Cloud
    print("\n4. Creating Cloud...")
    cloud = CloudServer()
    print(f"Created Cloud server")

    # Test cache system
    print("\n5. Testing cache system...")
    cache_system = CacheSystem(uavs, gbs_nodes, [mec], cloud)
    cache_system.populate_static_caches()

    # Test cache lookup
    location, hit = cache_system.lookup('map_0', 0)
    print(f"Cache lookup for 'map_0' by UAV 0: Location={location}, Hit={hit}")

    # Test UAV state
    print("\n6. Sample UAV state:")
    print(uavs[0].get_state())

    print("\n7. Sample GBS state:")
    print(gbs_nodes[0].get_state())

    print("\nTest completed successfully!")
